export default {
    home:'/',
    signin:'/signin',
    signup:'/signup',
    signupsuccess:'/signupsuccess',
    signupActivate:'/signup/activate/:token',
    memberDashboard:'/dashboard',
    memberSubscribe:'/dashboard/getpro',
    signUpSuccess:'/signup/success',
    logout:'/logout',
    getPro:'/dashboard/getpro',
    myVideos:'/dashboard/myvideos',
    guides:'/guide/:guide',
    buy:'/buy',
    about:'/about',
    manageSubscription:'/dashboard/mysubscription',
}